### ISSUE TITLE
Azure function v4 compatibility

### ISSUE THREAD

**Issue by JMourt** [logicmonitor/lm-logs-azure#32]
I redeployed this and found that it is still using a v3 version, which will lose support in December. I ran the upgrade compatibility checker and there are only some small issues that need to be fixed before the function can be upgraded. 

From MS:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cwindows%2Cin-process%2Cv4&pivots=programming-language-csharp#migrating-from-3x-to-4x

Beginning on December 3, 2022, function apps running on versions 2.x and 3.x of the Azure Functions runtime can no longer be supported. Before that time, please test, verify, and migrate your function apps to version 4.x of the Functions runtime. For more information, see [Migrating from 3.x to 4.x](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cwindows%2Cin-process%2Cv4&pivots=programming-language-csharp#migrating-from-3x-to-4x). After the deadline, function apps can be created and deployed, and existing apps continue to run. However, your apps won't be eligible for new features, security patches, performance optimizations, and support until you upgrade them to version 4.x.

End of support for these runtime versions is due to the ending of support for .NET Core 3.1, which is required by these older runtime versions. This requirement affects all Azure Functions runtime languages.
Functions version 1.x is still supported for C# function apps that require the .NET Framework. Preview support is now available in Functions 4.x to [run C# functions on .NET Framework 4.8](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#supported-versions).

**Comment by choudharypooja** [comment]
Hi JMourt 
Thanks for raising this issue.
We will definitely fix this before 3rd December and provide and updated implementation for the same.
Will keep you posted once we implement this.

**Comment by choudharypooja** [comment]
Hi @JMourt 
The issue is now resolved and the function is migrated from v3 to v4
